version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    environment:
      SONARQUBE_SCANNER_PARAMS: '{"sonar.host.url":"https://sonarcloud.io","sonar.projectKey":"revaturelabs_Curricula-UI","sonar.organization":"revaturelabs-screenforce"}'
    steps:
      - checkout
      - run:
          name: Install dependencies and test project
          command: |
            npm install
            npm run test
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud